from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Subject_Matter(Base):
	__tablename__ = 'subject_matter'
	id = Column(Integer, primary_key=True, index=True)
	episode = Column(String, nullable=False)
	title = Column(String, nullable=False)
	APPLE_FRAME = Column(Integer, nullable=False)
	AURORA_BOREALIS = Column(Integer, nullable=False)
	BARN = Column(Integer, nullable=False)
	BEACH = Column(Integer, nullable=False)
	BOAT = Column(Integer, nullable=False)
	BRIDGE = Column(Integer, nullable=False)
	BUILDING = Column(Integer, nullable=False)
	BUSHES = Column(Integer, nullable=False)
	CABIN = Column(Integer, nullable=False)
	CACTUS = Column(Integer, nullable=False)
	CIRCLE_FRAME = Column(Integer, nullable=False)
	CIRRUS = Column(Integer, nullable=False)
	CLIFF = Column(Integer, nullable=False)
	CLOUDS = Column(Integer, nullable=False)
	CONFIER = Column(Integer, nullable=False)
	CUMULUS = Column(Integer, nullable=False)
	DECIDUOUS = Column(Integer, nullable=False)
	DIANE_ANDRE = Column(Integer, nullable=False)
	DOCK = Column(Integer, nullable=False)
	DOUBLE_OVAL_FRAME = Column(Integer, nullable=False)
	FARM = Column(Integer, nullable=False)
	FENCE = Column(Integer, nullable=False)
	FIRE = Column(Integer, nullable=False)
	FLORIDA_FRAME = Column(Integer, nullable=False)
	FLOWERS = Column(Integer, nullable=False)
	FOG = Column(Integer, nullable=False)
	FRAMED = Column(Integer, nullable=False)
	GRASS = Column(Integer, nullable=False)
	GUEST = Column(Integer, nullable=False)
	HALF_CIRCLE_FRAME = Column(Integer, nullable=False)
	HALF_OVAL_FRAME = Column(Integer, nullable=False)
	HILLS = Column(Integer, nullable=False)
	LAKE = Column(Integer, nullable=False)
	LAKES = Column(Integer, nullable=False)
	LIGHTOUSE = Column(Integer, nullable=False)
	MILL = Column(Integer, nullable=False)
	MOON = Column(Integer, nullable=False)
	MOUNTAIN = Column(Integer, nullable=False)
	MOUNTAINS = Column(Integer, nullable=False)
	NIGHT = Column(Integer, nullable=False)
	OCEAN = Column(Integer, nullable=False)
	OVAL_FRAME = Column(Integer, nullable=False)
	PALM_TREES = Column(Integer, nullable=False)
	PathPath = Column(Integer, nullable=False)
	PERSON = Column(Integer, nullable=False)
	PORTRAIT = Column(Integer, nullable=False)
	RECTANGLE_3D_FRAME = Column(Integer, nullable=False)
	RECTANGULAR_FRAME = Column(Integer, nullable=False)
	RIVER = Column(Integer, nullable=False)
	ROCKS = Column(Integer, nullable=False)
	SEASHELL_FRAME = Column(Integer, nullable=False)
	SNOW = Column(Integer, nullable=False)
	SNOWY_MOUNTAIN = Column(Integer, nullable=False)
	SPLIT_FRAME = Column(Integer, nullable=False)
	STEVE_ROSS = Column(Integer, nullable=False)
	STRUCTURE = Column(Integer, nullable=False)
	SUN = Column(Integer, nullable=False)
	TOMB_FRAME = Column(Integer, nullable=False)
	TREE = Column(Integer, nullable=False)
	TREES = Column(Integer, nullable=False)
	TRIPLE_FRAME = Column(Integer, nullable=False)
	WATERFALL = Column(Integer, nullable=False)
	WAVES = Column(Integer, nullable=False)
	WINDMILL = Column(Integer, nullable=False)
	WINDOW_FRAME = Column(Integer, nullable=False)
	WINTER = Column(Integer, nullable=False)
	WOOD_FRAMED = Column(Integer, nullable=False)